saml-idp/saml_idp

lib/saml_idp/assertion_builder.rb
lib/saml_idp/controller.rb
lib/saml_idp/saml_response.rb
spec/lib/saml_idp/assertion_builder_spec.rb
spec/lib/saml_idp/saml_response_spec.rb

This makes sense because the AuthnContextClassRef can change
depending on the authentication level of the user which differs
per request.

Enable overriding of AuthnContextClassRef in the SamlIdp::Controller.

---

README.md

Resolves doc discrepancy for #17

name-id was converted to a struct for flexibility for configuration

---

lib/saml_idp/saml_response.rb

It looks like signed_assertion was intended to be private.

Fix private declaration

---

.travis.yml
lib/saml_idp.rb
lib/saml_idp/configurator.rb
lib/saml_idp/controller.rb
lib/saml_idp/logout_builder.rb
lib/saml_idp/logout_request_builder.rb
lib/saml_idp/logout_response_builder.rb
lib/saml_idp/metadata_builder.rb
lib/saml_idp/request.rb
lib/saml_idp/response_builder.rb
lib/saml_idp/service_provider.rb
lib/saml_idp/signable.rb
lib/saml_idp/signed_info_builder.rb
lib/saml_idp/version.rb
lib/saml_idp/xml_security.rb
saml_idp.gemspec
spec/lib/saml_idp/configurator_spec.rb
spec/lib/saml_idp/controller_spec.rb
spec/lib/saml_idp/logout_request_builder_spec.rb
spec/lib/saml_idp/logout_response_builder_spec.rb
spec/lib/saml_idp/metadata_builder_spec.rb
spec/lib/saml_idp/request_spec.rb
spec/support/saml_request_macros.rb
spec/xml_security_spec.rb

The newest `ruby-saml` library now supports single log out request/response. This PR adds corresponding support for that feature to IDPs.

Add support for SLO

---

saml_idp.gemspec

Add '>= 1.6.2' dependency for nokogiri. Version 1.6.1 and below causes saml_idp to create invalid saml responses. This can be seen easily as all validations in the saml_idp_controller_spec will fail with nokogiri 1.6.1 and below.

Update saml_idp.gemspec nokogiri dependency

---

README.md
lib/saml_idp/assertion_builder.rb
spec/lib/saml_idp/assertion_builder_spec.rb

New feature: if the `principal` passed to the AssertionBuilder responds to a method called `asserted_attributes` use the return value of that method rather than the global SamlIdp.config for a given SamlResponse.

Allow principal to assert its own attributes, rather than relying on global config

---

README.md
app/controllers/saml_idp/idp_controller.rb

Rails 5.0 deprecated before_filter in favor of before_action.  Rails 5.1 removes
before_filter.  before_action has been supported since Rails 4.  For Rails 3
continue to use before_filter.

Change before_filter to before_action for Rails >= 4

---

lib/saml_idp/metadata_builder.rb
spec/lib/saml_idp/metadata_builder_spec.rb

The builder for ContactPerson was attempting to use meta-programming to set 5
sub-fields: company, given_name, sur_name, telephone and email_address.  However,
each of these fields was creating a "Company" node under ContactPerson, like this:
```
<ContactPerson contactType="technical">
<Company>ACME Corporation</Company>
<Company>Road</Company>
<Company>Runner</Company>
<Company>mailto:acme@example.com</Company>
<Company>1-800-555-5555</Company>
</ContactPerson>
```
This is not valid according to the SAML spec.  When a program attempted to
validate the metadata XML document, it failed.  For our application, it meant
that occasionally we were getting errors reported.
This commit changes the ContactPerson node to be valid according to the SAML
spec.  After applying this commit, the above …

Fix ContactPerson XML Generation

---

lib/saml_idp/request.rb
spec/lib/saml_idp/request_spec.rb

**Why**: Without a valid issuer, a ServiceProvider for the Request cannot be located.

Request requires issuer

---

lib/saml_idp/incoming_metadata.rb

Why: SAML Metadata spec indicates that the ContactPerson element is an optional sequence allowing for 0 or more.
Ref: https://docs.oasis-open.org/security/saml/v2.0/saml-metadata-2.0-os.pdf line 399

Handle missing ContactPerson element

---

lib/saml_idp/service_provider.rb
saml_idp.gemspec

This change removes a dependency on the `HTTParty` gem. I figured a simple GET request is only needed in one place, so this private method could just use Ruby's built-in `Net::HTTP` class.

Remove HTTParty as dependency, use Net::HTTP instead

---

lib/saml_idp/controller.rb

see: https://github.com/rails/rails/blob/1099329be081297c16b02141ec13ca6a05ff037c/actionpack/lib/action_controller/metal/rendering.rb#L101-L104
`render :nothing` is deprecated and removed in Rails 5.1.

fixed render :nothing is deprecate

---

lib/saml_idp/encryptor.rb

See here: https://github.com/digidentity/xmlenc/blob/master/lib/xmlenc/encrypted_key.rb#L57 - corrected URI to proper format (point to ID=ED)

Fix issue with invalid DataReference URI

---

lib/saml_idp/incoming_metadata.rb
spec/lib/saml_idp/incoming_metadata_spec.rb

This code currently returns true if WantAssertionsSigned is present in the relying party metadata, rather than actually parsing the fields. This request is a simple bug fix with some tests. 
The original pull request is here: https://github.com/saml-idp/saml_idp/pull/98. I did a force push to my forked branch, which closed the request and wouldn't allow me to reopen it.

Fix signed assertions bug

---

README.md

Hi, first of all - thanks REALLY a lot for this awesome gem!
Here's a tiny fix on the document so as to support easier start for the gem users.
I found the configuration samples on `config.name_id.formats` slightly misleading, and am guessing this change will prevent issues like (https://github.com/saml-idp/saml_idp/issues/79).
Hope this helps!

update docs for config.name_id.format

---

lib/saml_idp/xml_security.rb

fixes signature verification for xml without explicit ds prefix and
custom digest algorithm.
This fixes verification of mod_auth_mellon signed authentication requests using anything else than sha1. This was (most probably) unearthed by an update to php-xml 7.3.9.

fix missing ns prefix for algorithm in signature verification code

---

.travis.yml
README.md
lib/saml_idp/controller.rb
lib/saml_idp/request.rb
lib/saml_idp/response_builder.rb
lib/saml_idp/saml_response.rb
lib/saml_idp/signable.rb
saml_idp.gemspec
spec/lib/saml_idp/response_builder_spec.rb
spec/lib/saml_idp/saml_response_spec.rb

This pull request contains 2 changes.
1. Signed response
Currently, gem only signing Assertion, but there are several patterns can be exists ([here is examples](https://www.samltool.com/generic_sso_res.php)) one of them is signed response.
2. Travis build fixes for Ruby and Rails version dependency issue

Signed SAML response to SP

---

README.md
lib/saml_idp.rb
lib/saml_idp/fingerprint.rb
spec/lib/saml_idp/fingerprint_spec.rb
spec/support/saml_request_macros.rb

extract existing code for integrator to be able to reuse
I am using this bit of code in my project to find a fingerprint
and I figured the best place to keep it, is within the gem itself.
I can rename the module
let me know
thanks

Add helper to create fingerprint from cert

---

lib/saml_idp/encryptor.rb

We ran into an issue with this keyname and the SP was refusing our IdP.
we just started working when we remove this line.
maybe we have configured something wrong?
should this be optional?
I wonder if removing it could affect others?
but this change helped us move forward.
thank you for reviewing

remove ds:KeyName when building encryption template

---

saml_idp.gemspec

since this other commit, it makes sense to bump the minimum version of ruby+rails
https://github.com/saml-idp/saml_idp/commit/26220a0c5eb7b3c833c88a3e3d13c480565ec2b4

bump minimum versions

---

Appraisals
gemfiles/rails_dev.gemfile

Another day I enabled GitHub document but it automatically affected our git hub action which was an unexpected result. Let me add the docs folder to support the public documentation site.

Support Github document

---

README.md

When we run `Fingerprint.certificate_digest(x509_cert, :sha512)` on console it gives error as `undefined local variable or method `x509_cert' for main:Object (NameError)`. Since `Fingerprint` class has been defined inside `SamlIdp`. By making this edit users can easily copy from ReadME

Added `SamlIdp::Fingerprint` instead `Fingerprint`

---

lib/saml_idp/request.rb
spec/lib/saml_idp/request_spec.rb

Original PR is https://github.com/saml-idp/saml_idp/pull/194 
----
Rails 7.1.0 introduces a new default logger class, ActiveSupport::BroadcastLogger, which does not inherit from Logger. (See: rails/rails#48615.)
Instead of testing for a specific class, we can test the interface.

Test logger interface instead of class

---

lib/saml_idp/controller.rb
spec/lib/saml_idp/controller_spec.rb
spec/support/saml_request_macros.rb

This fixes an issue in the `SamlIdp::Controller#encode_authn_response` method where arguments where being passed in the wrong order. This issue was introduced in v0.15.0.
In the call to `SamlResponse#initialize` the value of `false` for `signed_message_opts` was, by default, getting passed as the argument for `signed_assertion_opts` which caused SAML Responses to be generated without a signed assertion.
This wasn't caught in the tests because signed assertions were not checked when validating the SAML response, so a test was added to confirm that the assertion is being signed by default.
This could present a potential security concern, as SAML assertions are typically signed by default. It is expected that SAML Service Providers (SPs) validate these signatures. However, if a user of this …

Bug Fix: SAML Response Initialize Arguments Passed in the Wrong Order 

---

saml_idp.gemspec
spec/lib/saml_idp/controller_spec.rb
spec/spec_helper.rb
spec/support/saml_request_macros.rb

Decode AuthnRequest params to XML format before passing to mock.
I believe the percentage dropped after the recent fix because it was premature to establish a test limit percentage. This code contains many unnecessary "unit" tests, which I think should be replaced with appropriate SAML 2.0 workflow tests.

[fix] Flaky test

---

saml_idp.gemspec

It fixes a warning of loading ostruct gem from standard library with Ruby 3.3.5 and 3.4+.
The warning message is following:
```
/path/saml_idp/lib/saml_idp.rb:2: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```
- ruby: 3.3.5
- saml_idp gem: 1.6.0
- https://github.com/ruby/ruby/pull/10428
- https://bugs.ruby-lang.org/issues/20309

Fix warning: ostruct was loaded from the standard library

---

lib/saml_idp.rb
lib/saml_idp/configurator.rb
spec/lib/saml_idp/configurator_spec.rb

There is a case where the Rails gem is required but not fully initialized, such as when we require the ActionView gem. Therefore, instead of just checking if the `Rails` constant is available, we should be more precise and check if the required subsystem is available or initialized for us.

Check if Rails is fully initialized

---

README.md
lib/saml_idp/configurator.rb
lib/saml_idp/metadata_builder.rb
lib/saml_idp/signature_builder.rb
lib/saml_idp/signed_info_builder.rb
spec/lib/saml_idp/configurator_spec.rb

- allows for looking up x509 certificates with a proc in the SamlIdp config
- calls the proc or falls back to the original behavior where appropriate
- adds short example in the REDME documentation
This is an alternative approach to supporting multiple x509 certificates, secret keys, and password. This uses procs in the SamlIdp configuration as an alternative to #186 and #209.
I have been using this approach for some time now using a service object as a finder for the appropriate cert and secret key.
Some examples for looking these up:
```ruby
config.x509_certificate = -> { File.read("cert.pem") }
config.secret_key = -> { SecretKeyFinder.key_for(id: 1) }
config.password = -> { Rails.application.credentials.dig(:saml_idp, :password ) }
```

Alternative to support multiple x509 Certificates via procs

---

lib/saml_idp/controller.rb
spec/lib/saml_idp/controller_spec.rb

Setting `nil` and `false` for `signed_assertion` always results in `true`, preventing the application from changing the value.

[bug] Make assertion signature flag switchable

---

.github/workflows/ci.yml
Appraisals
gemfiles/rails_6.1.gemfile
gemfiles/rails_7.0.gemfile
gemfiles/rails_8.0.gemfile

This Pull Request adds Ruby 3.4 and Rails 8.0/7.2 to the CI matrix.
The `bigdecimal` and `mutex_m` gems have been added to the Appraisals file for Rails versions <= 7.0.
This is necessary because these gems were changed from default gems to bundled gems in Ruby 3.4 and later, and bundled gems must be explicitly declared.
- https://bugs.ruby-lang.org/issues/20187
Additionally, `concurrent-ruby` v1.3.4 has been added for compatibility with Rails versions <= 7.1.
This resolves an error that occurs with Rails <= 7.0 and `concurrent-ruby` v1.3.5:
- https://github.com/rails/rails/issues/54260

Add Ruby 3.4 and Rails 8.0/7.2 to CI matrix
